# Generated by Django 4.2.2 on 2023-06-08 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRooms',
            new_name='UsersRoom',
        ),
    ]
